from __future__ import annotations

import argparse
import hashlib
import json
import re
import time
import urllib.parse
import urllib.request
from pathlib import Path

import pandas as pd

from ggst_aliases import GGST_PAGE_OVERRIDES
import ggst_frame_data


SF6_API_URL = "https://wiki.supercombo.gg/api.php"
GGST_API_URL = "https://www.dustloop.com/wiki/api.php"
USER_AGENT = "Mozilla/5.0 (compatible; Bub frame image cache builder/1.0)"
FRAME_IMAGE_THUMB_WIDTH = 220
SF6_BOTTOM_IMAGE_WIDTH = 262


def normalize_key(value: object) -> str:
    return re.sub(r"[^a-z0-9]", "", str(value or "").lower())


def wiki_request(api_url: str, params: dict[str, object], sleep_seconds: float) -> dict:
    query = urllib.parse.urlencode(params)
    request = urllib.request.Request(f"{api_url}?{query}", headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        data = json.loads(response.read().decode("utf-8"))
    if sleep_seconds:
        time.sleep(sleep_seconds)
    return data


def chunks(values: list[str], size: int) -> list[list[str]]:
    return [values[index : index + size] for index in range(0, len(values), size)]


def resolve_file_urls(api_url: str, filenames: list[str], thumb_width: int, sleep_seconds: float) -> dict[str, str]:
    results: dict[str, str] = {}
    unique_names = []
    seen = set()
    for filename in filenames:
        clean_name = str(filename or "").strip().replace("_", " ")
        if not clean_name or clean_name.lower() in seen:
            continue
        seen.add(clean_name.lower())
        unique_names.append(clean_name)

    for batch in chunks(unique_names, 20):
        titles = "|".join(f"File:{name}" for name in batch)
        data = wiki_request(
            api_url,
            {
                "action": "query",
                "titles": titles,
                "prop": "imageinfo",
                "iiprop": "url",
                "iiurlwidth": thumb_width,
                "format": "json",
            },
            sleep_seconds,
        )
        for page in (data.get("query", {}).get("pages", {}) or {}).values():
            title = str(page.get("title", ""))
            if page.get("missing") or not title.startswith("File:"):
                continue
            image_info = (page.get("imageinfo") or [{}])[0]
            url = image_info.get("thumburl") or image_info.get("url")
            if not url:
                continue
            filename = title.split(":", 1)[1]
            results[filename.lower()] = url
            results[filename.replace(" ", "_").lower()] = url
    return results


def file_redirect_url(api_url: str, filename: str) -> str:
    base_url = api_url.rsplit("/api.php", 1)[0]
    encoded = urllib.parse.quote(str(filename or "").strip().replace(" ", "_"), safe="._()-")
    return f"{base_url}/Special:Redirect/file/{encoded}"


def mediawiki_thumb_url(api_url: str, filename: str, thumb_width: int = FRAME_IMAGE_THUMB_WIDTH) -> str:
    base_url = api_url.rsplit("/api.php", 1)[0]
    normalized_name = str(filename or "").strip().replace(" ", "_")
    digest = hashlib.md5(normalized_name.encode("utf-8")).hexdigest()
    encoded_name = urllib.parse.quote(normalized_name, safe="._()-")
    return f"{base_url}/images/thumb/{digest[0]}/{digest[:2]}/{encoded_name}/{thumb_width}px-{encoded_name}"


def write_python_cache(path: Path, variable_name: str, data: dict) -> None:
    path.write_text(
        f"# Generated by build_move_image_caches.py. Do not edit by hand.\n"
        f"{variable_name} = {json.dumps(data, indent=2, sort_keys=True)}\n",
        encoding="utf-8",
    )


def sf6_page_title(character_label: str) -> str:
    page_overrides = {
        "C.Viper": "C._Viper",
        "E.Honda": "E._Honda",
        "M.Bison": "M._Bison",
    }
    return f"Street_Fighter_6/{page_overrides.get(character_label, character_label.replace(' ', '_'))}"


def fetch_sf6_page_images(character_label: str, sleep_seconds: float) -> list[str]:
    data = wiki_request(
        SF6_API_URL,
        {
            "action": "parse",
            "page": sf6_page_title(character_label),
            "prop": "images",
            "format": "json",
        },
        sleep_seconds,
    )
    return list((data.get("parse") or {}).get("images") or [])


def sf6_image_move_key(filename: str) -> str:
    stem = re.sub(r"\.(?:png|webp|gif|jpg|jpeg)$", "", filename, flags=re.IGNORECASE)
    if not stem.lower().startswith("sf6_"):
        return ""
    parts = stem.split("_")
    if len(parts) < 3:
        return ""
    suffix = "_".join(parts[2:])
    if any(token in suffix.lower() for token in ("hitbox", "icon", "portrait")):
        return ""
    return normalize_key(suffix)


def build_sf6_cache(workbook_path: Path, output_path: Path, sleep_seconds: float, resolve_urls: bool) -> int:
    xls = pd.ExcelFile(workbook_path, engine="odf")
    cache: dict[str, dict[str, str]] = {}
    filenames_to_resolve: list[str] = []
    pending: dict[tuple[str, str], str] = {}

    for sheet_name in xls.sheet_names:
        if not sheet_name.endswith("Normal"):
            continue
        character_label = sheet_name[: -len("Normal")].rstrip(".")
        df = pd.read_excel(xls, sheet_name=sheet_name).fillna("")
        row_keys = {normalize_key(row.get("numCmd")): str(row.get("numCmd", "")).strip() for row in df.to_dict("records")}
        if not row_keys:
            continue
        try:
            images = fetch_sf6_page_images(character_label, sleep_seconds)
        except Exception as exc:
            print(f"[sf6-images] skipped {character_label}: {exc}", flush=True)
            continue
        for image in images:
            move_key = sf6_image_move_key(image)
            if move_key not in row_keys:
                continue
            pending[(normalize_key(character_label), row_keys[move_key])] = image
            filenames_to_resolve.append(image)

    urls = resolve_file_urls(SF6_API_URL, filenames_to_resolve, thumb_width=SF6_BOTTOM_IMAGE_WIDTH, sleep_seconds=sleep_seconds) if resolve_urls else {}
    for (char_key, move_key), filename in pending.items():
        url = urls.get(filename.lower()) or urls.get(filename.replace(" ", "_").lower()) or mediawiki_thumb_url(SF6_API_URL, filename, thumb_width=SF6_BOTTOM_IMAGE_WIDTH)
        if not url:
            continue
        cache.setdefault(char_key, {})[move_key] = url

    write_python_cache(output_path, "SF6_MOVE_IMAGE_URLS", cache)
    return sum(len(moves) for moves in cache.values())


def ggst_page_title(character_label: str) -> str:
    page_name = GGST_PAGE_OVERRIDES.get(character_label, character_label.replace(" ", "_"))
    return f"GGST/{page_name}"


def fetch_ggst_page_images(character_label: str, sleep_seconds: float) -> list[str]:
    data = wiki_request(
        GGST_API_URL,
        {
            "action": "parse",
            "page": ggst_page_title(character_label),
            "prop": "images",
            "format": "json",
        },
        sleep_seconds,
    )
    return list((data.get("parse") or {}).get("images") or [])


def ggst_filename_move_key(filename: str, character_label: str, hitbox: bool) -> str:
    stem = re.sub(r"\.(?:png|webp|gif|jpg|jpeg)$", "", filename, flags=re.IGNORECASE)
    if not stem.lower().startswith("ggst_"):
        return ""
    if any(token in stem.lower() for token in ("portrait", "icon", "navigation", "color")):
        return ""
    if hitbox != ("hitbox" in stem.lower()):
        return ""
    text = stem.lower()
    character_tokens = [character_label]
    if character_label in GGST_PAGE_OVERRIDES:
        character_tokens.append(GGST_PAGE_OVERRIDES[character_label].replace("_", " "))
    for token in sorted(character_tokens, key=len, reverse=True):
        compact = re.sub(r"[^a-z0-9]+", "_", token.lower()).strip("_")
        text = re.sub(rf"^ggst_{re.escape(compact)}_", "", text)
    text = re.sub(r"^ggst_[a-z0-9.\-]+_", "", text)
    text = re.sub(r"_?hitbox(?:_preview)?(?:_?\d+)?$", "", text)
    text = re.sub(r"_\d+$", "", text)
    text = text.replace("_", "")
    return ggst_frame_data.normalize_move_token(text)


def build_ggst_cache(workbook_path: Path, output_path: Path, sleep_seconds: float, resolve_urls: bool) -> tuple[int, int]:
    xls = pd.ExcelFile(workbook_path, engine="odf")
    normal_pending: dict[tuple[str, str], str] = {}
    hitbox_pending: dict[tuple[str, str], list[str]] = {}
    filenames: list[str] = []

    for sheet_name in xls.sheet_names:
        if not sheet_name.endswith("Normal") or sheet_name in {"IdealSheetNormal", "TemplateNormal"}:
            continue
        character_label = sheet_name[: -len("Normal")]
        char_key = ggst_frame_data.resolve_character_key(character_label) or character_label.strip().lower()
        df = pd.read_excel(xls, sheet_name=sheet_name).fillna("")
        row_keys = set()
        for row in df.to_dict("records"):
            for key_field in ("numCmd", "dustloopKey"):
                move_key = str(row.get(key_field, "")).strip()
                if move_key:
                    row_keys.add(ggst_frame_data.normalize_move_token(move_key))
        if not row_keys:
            continue
        try:
            images = fetch_ggst_page_images(character_label, sleep_seconds)
        except Exception as exc:
            print(f"[ggst-images] skipped {character_label}: {exc}", flush=True)
            continue
        for image in images:
            normal_key = ggst_filename_move_key(image, character_label, hitbox=False)
            if normal_key in row_keys and (char_key, normal_key) not in normal_pending:
                normal_pending[(char_key, normal_key)] = image
                filenames.append(image)
            hitbox_key = ggst_filename_move_key(image, character_label, hitbox=True)
            if hitbox_key in row_keys:
                hitbox_pending.setdefault((char_key, hitbox_key), []).append(image)
                filenames.append(image)

    urls = resolve_file_urls(GGST_API_URL, filenames, thumb_width=FRAME_IMAGE_THUMB_WIDTH, sleep_seconds=sleep_seconds) if resolve_urls else {}
    normal_cache = {}
    hitbox_cache = {}
    for (char_key, move_key), filename in normal_pending.items():
        url = urls.get(filename.lower()) or urls.get(filename.replace(" ", "_").lower()) or mediawiki_thumb_url(GGST_API_URL, filename)
        if url:
            normal_cache.setdefault(char_key, {})[move_key] = url
    for (char_key, move_key), filenames_for_move in hitbox_pending.items():
        move_urls = [urls.get(name.lower()) or urls.get(name.replace(" ", "_").lower()) or mediawiki_thumb_url(GGST_API_URL, name) for name in filenames_for_move]
        move_urls = [url for url in move_urls if url]
        if move_urls:
            hitbox_cache.setdefault(char_key, {})[move_key] = move_urls

    output_path.write_text(
        "# Generated by build_move_image_caches.py. Do not edit by hand.\n"
        f"GGST_MOVE_IMAGE_URLS = {json.dumps(normal_cache, indent=2, sort_keys=True)}\n\n"
        f"GGST_HITBOX_DATA = {json.dumps(hitbox_cache, indent=2, sort_keys=True)}\n",
        encoding="utf-8",
    )
    return (
        sum(len(moves) for moves in normal_cache.values()),
        sum(len(links) for moves in hitbox_cache.values() for links in moves.values()),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build remote image URL caches for SF6 and GGST frame embeds.")
    parser.add_argument("--sf6-workbook", default="FAT - SF6 Frame Data.ods")
    parser.add_argument("--ggst-workbook", default="GGST Frame Data.ods")
    parser.add_argument("--sf6-output", default="sf6_move_images.py")
    parser.add_argument("--ggst-output", default="ggst_move_images.py")
    parser.add_argument("--sleep", type=float, default=0.1)
    parser.add_argument("--resolve-urls", action="store_true", help="Resolve file URLs through the wiki API instead of deriving direct thumbnail URLs locally.")
    parser.add_argument("--skip-sf6", action="store_true")
    parser.add_argument("--skip-ggst", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.skip_sf6:
        count = build_sf6_cache(Path(args.sf6_workbook), Path(args.sf6_output), args.sleep, args.resolve_urls)
        print(f"Wrote {args.sf6_output}: {count} SF6 move image links")
    if not args.skip_ggst:
        normal_count, hitbox_count = build_ggst_cache(Path(args.ggst_workbook), Path(args.ggst_output), args.sleep, args.resolve_urls)
        print(f"Wrote {args.ggst_output}: {normal_count} GGST move image links, {hitbox_count} GGST hitbox links")


if __name__ == "__main__":
    main()
