"""Output helpers shared by maintained data-generation scripts."""
# Generation helpers keep workbook and Python-cache serialization deterministic across scrapers.

from __future__ import annotations

import json
import re
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any


def normal_sheet_name(
    display_name: str,
    suffix: str = "Normal",
    fallback: str = "CharacterNormal",
    *,
    allow_period: bool = False,
) -> str:
    """Return a stable ODS sheet name within LibreOffice's 31-character limit."""
    pattern = r"[^A-Za-z0-9.]+" if allow_period else r"[^A-Za-z0-9]+"
    compact = re.sub(pattern, "", str(display_name or ""))
    return (f"{compact}{suffix}"[:31]) or fallback[:31]


def write_ods_sheets(
    path: Path,
    sheets: Mapping[str, Sequence[Mapping[str, Any]]],
    columns: Sequence[str] | None = None,
) -> None:
    """Write row mappings to named ODS sheets, adding missing columns as empty values."""
    import pandas as pd

    with pd.ExcelWriter(path, engine="odf") as writer:
        for sheet_name, rows in sheets.items():
            frame = pd.DataFrame(list(rows))
            if columns is not None:
                for column in columns:
                    if column not in frame.columns:
                        frame[column] = ""
                frame = frame[list(columns)]
            frame.to_excel(writer, sheet_name=str(sheet_name)[:31], index=False)


def write_python_constants(
    path: Path,
    constants: Mapping[str, Any],
    generated_by: str,
    *,
    ensure_ascii: bool = True,
) -> None:
    """Serialize generated Python constants deterministically without importing them."""
    lines = [f"# Generated by {generated_by}. Do not edit by hand."]
    for name, value in constants.items():
        lines.append(f"{name} = {json.dumps(value, indent=2, sort_keys=True, ensure_ascii=ensure_ascii)}")
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
